// Signs release builds with the upload key when CI provides it (see
// .github/workflows/android-release.yml). android/ is generated by `expo prebuild`,
// so the signing config is added here rather than by editing build.gradle.
//
// Without MOBY_UPLOAD_STORE_FILE (local builds, forks) nothing changes: release
// builds keep Expo's default (debug) signing and are not uploadable to Play.
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// @moby/release-signing';

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes(MARKER)) return cfg;
    cfg.modResults.contents += `
${MARKER}
def mobyStoreFile = System.getenv("MOBY_UPLOAD_STORE_FILE")
if (mobyStoreFile) {
    android.signingConfigs.create("mobyUpload") {
        storeFile file(mobyStoreFile)
        storePassword System.getenv("MOBY_UPLOAD_STORE_PASSWORD")
        keyAlias System.getenv("MOBY_UPLOAD_KEY_ALIAS")
        keyPassword System.getenv("MOBY_UPLOAD_KEY_PASSWORD")
    }
    android.buildTypes.release.signingConfig android.signingConfigs.mobyUpload
}
`;
    return cfg;
  });
};
