// Names the release APK `Moby.apk` (instead of `app-release.apk`).
// android/ is generated by `expo prebuild`, so this is applied as a config plugin
// rather than by editing android/app/build.gradle by hand.
//
// Debug builds keep the default `app-debug.apk`: `expo run:android` looks for that
// exact file when installing on a device.
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// @moby/apk-name';

module.exports = function withApkName(config, { name = 'Moby' } = {}) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes(MARKER)) return cfg;
    cfg.modResults.contents += `
${MARKER}
android.applicationVariants.all { variant ->
    if (variant.buildType.name == "release") {
        variant.outputs.all { outputFileName = "${name}.apk" }
    }
}
`;
    return cfg;
  });
};
