// Removes expo-location's background LocationTaskService from the merged manifest.
// Moby only reads location in the foreground; declaring a `location` foreground service
// would make Google Play ask for a foreground-service declaration and video proof.
// android/ is generated by `expo prebuild`, so this is a config plugin.
const { withAndroidManifest } = require('expo/config-plugins');

const SERVICE = 'expo.modules.location.services.LocationTaskService';

module.exports = function withoutLocationService(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    manifest.$['xmlns:tools'] = manifest.$['xmlns:tools'] ?? 'http://schemas.android.com/tools';
    const app = manifest.application[0];
    app.service = (app.service ?? []).filter((s) => s.$['android:name'] !== SERVICE);
    app.service.push({ $: { 'android:name': SERVICE, 'tools:node': 'remove' } });
    return cfg;
  });
};
