/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Client feature flags and runtime config
         * @description Clients MUST gate post-core features on these flags rather than shipping them unconditionally. Supports the feature-flag discipline in the plan: a half-built feature is flagged off, not half-shown.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientConfig"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a user account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        display_name?: string;
                        home_region: components["schemas"]["RegionCode"];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh an access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a push token for this device
         * @description push_provider is explicit rather than inferred so non-FCM regions can be added later without a contract change.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Stable client-generated UUID */
                        device_id: string;
                        /** @enum {string} */
                        push_provider: "fcm" | "apns";
                        push_token: string;
                        /** @enum {string} */
                        platform: "ios" | "android";
                    };
                };
            };
            responses: {
                /** @description Registered */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a manual ground report
         * @description Written to storage before processing, so a 202 means durably received. client_event_id is the idempotency key — retries are safe.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReportSubmission"];
                };
            };
            responses: {
                /** @description Accepted for processing */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportAccepted"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fused event detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    event_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm or deny an existing event (proximity prompt response)
         * @description Binary response tied to an existing event rather than a new report, so confirmations never spawn duplicate look-alike events. observed_at_location indicates the responder actually reached the reported coordinates — a negative response only carries downgrade weight when this is true.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    event_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        response: "confirm" | "deny" | "unsure";
                        observed_at_location: boolean;
                        /** Format: date-time */
                        observed_at: string;
                        location?: components["schemas"]["GeoPoint"];
                    };
                };
            };
            responses: {
                /** @description Recorded */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Situational brief for an event
         * @description Generated asynchronously on Ultra after the fast alert has already been sent. Returns 202 with status "pending" while generation is in flight — clients should render the alert immediately and let the brief arrive behind it. Never block alert display on this endpoint.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    event_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Brief ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SituationalBrief"];
                    };
                };
                /** @description Generation in flight */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "pending";
                            retry_after_seconds?: number;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{region}/cascade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active compound-hazard assessment for a region
         * @description Ultra reasons across all active regional events to detect cascading systems (quake to landslide to river dam to flood) that no single-event view surfaces. Only produced when a region has 2+ active events above Tier 0; otherwise 204.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    region: components["schemas"]["RegionCode"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CascadeAssessment"];
                    };
                };
                /** @description No active cascade assessment for this region */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guidance/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manifest of available guidance card bundles
         * @description Clients sync bundles while connected so cards remain readable with zero signal. Compare local content_hash against the manifest to decide what to re-download. Cards are authored by Ultra from official sources.
         */
        get: {
            parameters: {
                query?: {
                    region?: components["schemas"]["RegionCode"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            bundles?: components["schemas"]["GuidanceBundle"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guidance/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guidance cards for a region and hazard */
        get: {
            parameters: {
                query: {
                    region: components["schemas"]["RegionCode"];
                    hazard_type?: components["schemas"]["HazardType"];
                    bundle_version?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cards?: components["schemas"]["GuidanceCard"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active alerts
         * @description Returns Tier 2 (public) alerts by default. Lower tiers are visible only to reviewers, or to subscribers who opt into early/unverified signals.
         */
        get: {
            parameters: {
                query?: {
                    region?: components["schemas"]["RegionCode"];
                    lat?: number;
                    lon?: number;
                    radius_km?: number;
                    min_tier?: 0 | 1 | 2;
                    since?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            alerts?: components["schemas"]["Alert"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alert detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    alert_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List region subscriptions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Subscription"][];
                    };
                };
            };
        };
        put?: never;
        /** Subscribe to an area */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        region: components["schemas"]["RegionCode"];
                        label?: string;
                        center: components["schemas"]["GeoPoint"];
                        radius_km: number;
                        /**
                         * @default medium
                         * @enum {string}
                         */
                        min_severity?: "low" | "medium" | "high" | "critical";
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Subscription"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a subscription */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    subscription_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mesh/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload mesh-relayed records from a gateway device
         * @description Idempotent on event_id. A repeated event_id is never a duplicate event — it either no-ops or adds a relay hash to the existing record. Safe to retry until acknowledged.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        device_id: string;
                        records: components["schemas"]["MeshRecord"][];
                    };
                };
            };
            responses: {
                /** @description Sync result — acked ids may be cleared from the local queue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            acknowledged?: string[];
                            rejected?: {
                                event_id?: string;
                                reason?: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mesh/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active alerts in compact form for mesh injection */
        get: {
            parameters: {
                query: {
                    lat: number;
                    lon: number;
                    radius_km?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            records?: components["schemas"]["MeshRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events awaiting human review
         * @description Reviewer role required. Severity-floor items sort first.
         */
        get: {
            parameters: {
                query?: {
                    region?: components["schemas"]["RegionCode"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewItem"][];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{event_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve, reject, or hold an event
         * @description Resumes the paused LangGraph checkpoint for this event.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    event_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        decision: "approve" | "reject" | "hold";
                        note?: string;
                        /** @enum {string} */
                        override_severity?: "low" | "medium" | "high" | "critical";
                    };
                };
            };
            responses: {
                /** @description Recorded */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        ClientConfig: {
            min_supported_client: string;
            /** @description Post-core features. Clients gate UI on these. Absent or false means the feature is not shown at all — never partially rendered. */
            flags: {
                /** @default false */
                situational_brief: boolean;
                /** @default false */
                cascade_analysis: boolean;
                /** @default false */
                offline_guidance_cards: boolean;
                /** @default false */
                on_device_assistant: boolean;
                /** @default false */
                mesh_relay: boolean;
                /** @default false */
                proximity_confirmation: boolean;
                /** @default false */
                early_tier_opt_in: boolean;
            };
        };
        /**
         * @description Enabled regions. v1 ships US only; CN is reserved and rejected at runtime until its feed, coordinate-frame and push work lands.
         * @enum {string}
         */
        RegionCode: "US" | "CN";
        /**
         * @description Declared per region so clients never assume WGS-84. v1 is always WGS84.
         * @enum {string}
         */
        CoordinateFrame: "WGS84" | "GCJ02";
        GeoPoint: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            accuracy_m?: number;
            /** @default WGS84 */
            frame: components["schemas"]["CoordinateFrame"];
        };
        /** @enum {string} */
        HazardType: "flood" | "fire" | "earthquake" | "storm" | "landslide" | "other";
        /**
         * @description Controlled vocabulary — lets fusion match reports of the same phenomenon.
         * @enum {string}
         */
        ObservedEffect: "rising_water" | "structural_damage" | "smoke_or_fire_visible" | "ground_shaking" | "blocked_road" | "other";
        /** @enum {string} */
        Severity: "low" | "medium" | "high" | "critical";
        /** @enum {string} */
        SourceType: "official" | "manual" | "mesh";
        AuthTokens: {
            access_token: string;
            refresh_token: string;
            /** @description Seconds */
            expires_in: number;
        };
        User: {
            user_id: string;
            /** Format: email */
            email: string;
            display_name?: string;
            roles: ("subscriber" | "reporter" | "reviewer" | "admin")[];
            home_region: components["schemas"]["RegionCode"];
            /** Format: date-time */
            created_at?: string;
        };
        ReportSubmission: {
            /** @description Client-generated UUID. Idempotency key — safe to retry. */
            client_event_id: string;
            hazard_type: components["schemas"]["HazardType"];
            observed_effect?: components["schemas"]["ObservedEffect"];
            severity: components["schemas"]["Severity"];
            location: components["schemas"]["GeoPoint"];
            /** Format: date-time */
            observed_at: string;
            /** @description Free text. Parsed by the structuring agent; never relayed over mesh. */
            note?: string;
            /**
             * @description True if queued on-device before connectivity returned.
             * @default false
             */
            captured_offline: boolean;
        };
        ReportAccepted: {
            client_event_id: string;
            /** @description Fused event this report was attached to */
            event_id: string;
            /** @enum {integer} */
            tier: 0 | 1 | 2;
            merged_into_existing?: boolean;
        };
        Event: {
            event_id: string;
            source: components["schemas"]["SourceType"];
            region?: components["schemas"]["RegionCode"];
            hazard_type: components["schemas"]["HazardType"];
            observed_effect?: components["schemas"]["ObservedEffect"];
            severity: components["schemas"]["Severity"];
            location: components["schemas"]["GeoPoint"];
            /** Format: date-time */
            first_reported_at?: string;
            /** Format: date-time */
            last_updated_at?: string;
            /**
             * @description 0 unverified, 1 corroborated, 2 confirmed (public alert)
             * @enum {integer}
             */
            tier: 0 | 1 | 2;
            confidence: number;
            specificity_score?: number;
            /** @description Distinct originators only — relay hops never increment this. */
            distinct_reporter_count?: number;
            confirm_count?: number;
            deny_count?: number;
            /** @description Matching NOAA/USGS/EONET/GDACS event, if any. */
            official_match_id?: string | null;
            /** @enum {string|null} */
            reviewer_decision?: "approve" | "reject" | "hold" | null;
            /**
             * @description Situational brief generation state. Clients never block on this.
             * @default not_requested
             * @enum {string}
             */
            brief_status: "not_requested" | "pending" | "ready" | "failed";
            /**
             * @description Shown verbatim in UI — unverified reports must never render as official.
             * @enum {string}
             */
            verification_label?: "unverified_report" | "corroborated_report" | "official_confirmed";
        };
        Alert: {
            alert_id: string;
            event_id: string;
            headline: string;
            body?: string;
            severity: components["schemas"]["Severity"];
            location?: components["schemas"]["GeoPoint"];
            affected_radius_km?: number;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            expires_at?: string;
            /** @enum {string} */
            verification_label: "unverified_report" | "corroborated_report" | "official_confirmed";
            /** @description e.g. "NOAA/NWS" or "Community reports" */
            source_attribution?: string;
            /** @description Same value as the fused Event. Clients fall back to a generic icon when absent. */
            hazard_type?: components["schemas"]["HazardType"];
            /** @description Human-readable place for the alert's location, e.g. "Russian River Basin". Shown beside distance and time; never repeated in the headline. */
            location_name?: string;
            /** @description Distinct originating reporters behind a corroborated_report (relay hops and repeat reports from one device do not count — see escalation caution rules). Omitted for official_confirmed; 1 or omitted for unverified_report. */
            corroboration_count?: number;
        };
        SituationalBrief: {
            event_id: string;
            /** Format: date-time */
            generated_at: string;
            /** @description e.g. nemotron-3-ultra */
            model: string;
            /** @description What is likely happening, in plain language. */
            summary: string;
            /** @description Plausible near-term development. Explicitly an estimate. */
            likely_progression?: string;
            /** @description Downstream or adjacent areas that may be affected. */
            exposed_areas?: {
                description?: string;
                location?: components["schemas"]["GeoPoint"];
                rationale?: string;
            }[];
            /** @description Guidance drawn from matched official sources, attributed. */
            official_guidance?: string;
            /** @description Required. What the brief does not know and where it may be wrong. Clients MUST display this — never render a brief as certainty. */
            uncertainty: string;
            sources?: string[];
        };
        CascadeAssessment: {
            region: components["schemas"]["RegionCode"];
            /** Format: date-time */
            generated_at: string;
            model?: string;
            /** @description Whether active events appear to be one compound system. */
            is_cascade: boolean;
            confidence?: number;
            event_ids: string[];
            /** @description Proposed causal ordering, if a cascade is detected. */
            chain?: {
                event_id?: string;
                /** @description e.g. trigger */
                role?: string;
            }[];
            reasoning: string;
            uncertainty?: string;
        };
        GuidanceBundle: {
            bundle_id: string;
            region: components["schemas"]["RegionCode"];
            hazard_types?: components["schemas"]["HazardType"][];
            version: string;
            /** @description Compare against local copy to decide re-download */
            content_hash: string;
            size_bytes: number;
            /** Format: date-time */
            generated_at: string;
            card_count?: number;
        };
        GuidanceCard: {
            card_id: string;
            hazard_type: components["schemas"]["HazardType"];
            /** @description Short condition string used for local retrieval matching. */
            applies_when?: string;
            title: string;
            /** @description Actionable guidance traceable to the cited official source. Content is synthesized by Ultra from official material, not authored freely. */
            body: string;
            /** @description Lower is more urgent. Drives static fallback ordering. */
            priority?: number;
            /** @description e.g. FEMA */
            source_name: string;
            source_url: string;
            /**
             * Format: date-time
             * @description MUST be displayed. Offline guidance goes stale and the user needs to see how old it is.
             */
            last_reviewed_at: string;
            /**
             * @description Included in the hard-coded, model-independent fallback set. These render even if retrieval or the on-device model is unavailable.
             * @default false
             */
            is_critical_fallback: boolean;
        };
        /** @description JSON mirror of the ~28-byte binary record relayed over BLE. The wire format is CBOR/packed-binary; this shape is only used at the gateway sync boundary. */
        MeshRecord: {
            /** @description 8-byte truncated hash */
            event_id: string;
            hazard_type: number;
            /** @description Degrees times 1e6 */
            lat_e6: number;
            /** @description Degrees times 1e6 */
            lon_e6: number;
            severity: number;
            confidence?: number;
            hop_count: number;
            /** @description Unix epoch seconds */
            timestamp: number;
            /** @description 4-byte anonymized originator */
            reporter_hash: string;
            /** @description Relay hashes observed by this gateway. Never counted as corroboration. */
            relayed_by?: string[];
        };
        Subscription: {
            subscription_id: string;
            region: components["schemas"]["RegionCode"];
            label?: string;
            center: components["schemas"]["GeoPoint"];
            radius_km: number;
            min_severity: components["schemas"]["Severity"];
        };
        ReviewItem: {
            event_id: string;
            event: components["schemas"]["Event"];
            /** Format: date-time */
            queued_at: string;
            /** @enum {string} */
            reason: "tier1_corroborated" | "severity_floor" | "conflicting_reports" | "low_confidence";
            contributing_reports?: components["schemas"]["ReportSubmission"][];
            /** @description If the agentic adjudicator deferred or hit its budget, its reasoning is surfaced here so the reviewer sees why. */
            adjudicator_rationale?: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required or invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
